### ISSUE TITLE
downloading meshes error

### ISSUE THREAD

**Issue by David-Berson** [serre-lab/webknossos#1]
Hi. 

So great to have this platform for efficient two-way communication.  So adaptive!

OK, so here' my first issue. I'm looking ahead to getting reconstructed cellular volumes into Amira for further processing. Surfaces of cells (cellID volumes) are supposed to be downloadable from wK using the Meshes tab of the top menu bar (far right).  The  Download option is supposed to save an  STS file (surface mesh) of the active cellID.  I'm pretty sure Amira knows about STL, because it uses this file type for output. I'm assuming they can import as well. So worth a try.

But when I select a cellID in wK and try to download, I get an error.  It turns out to be impossible to cut and paste the text from the error so I've tried to transcribe the beginning at the end of this message. But you can reproduce the error yourself. 

I did try to do this on German wK as well, but I had other issues there I didn't have time to troubleshoot.
 
Thanks!
------------------------------------------------

Internal error

TypeError: Cannot read property 'transverse' of undefined TypeError:
Cannot read property 'transverse' of undefined.

at b.STLExporter.n [as parse] https://connectomics.clps.brown.edu/assets/bundle/main.js?
nocache=e56d36edc0..._

**Comment by David-Berson** [comment]
Resolved!  You have to have isosurface rendering enabled.  Load the dataset using the View option, then under Settings (gear icon) Dataset  set the Render Isosurfaces (beta) switch to ON.   Shift left click in the ortho slice views on the segment you want and it should appear in the 3D view at lower right. Now the Download button under Meshes downloads an STL file of that isosurface.

**Comment by David-Berson** [comment]
Am I right that wK only allows you to see these beautiful rendered meshes of whatever volume you want in View mode?  For curation, you need to be able to go back and forth all the time between a place where you think two segments should be fused and a 3D view of what bits you're dealing with.  There's no way you can keep going in and out of View vs. Trace mode every time you have a question to resolve.  If I'm right about the current limitation, it could be a heavy lift to get into the guts of wK and fit the problem,, but all the pieces are there for wK to be able to do this, no?

**Comment by drewlinsley** [comment]
It does seem that way, and there's an open issue on wK about this: https://github.com/scalableminds/webknossos/issues/3681

They are super responsive, so it might help if we post to say this is a must-have function.
