### ISSUE TITLE
Missing intermediate zoom (mag) level

### ISSUE THREAD

**Issue by David-Berson** [serre-lab/webknossos#6]
The very low and very highest resolutions of the EM data are available, but the data are missing at an intermediate zoom level.  In my hands, the EM data go black at zoom levels for which the scale bar shown ranges from ~2 to ~4 um.

**Comment by drewlinsley** [comment]
On it. Running the official command now:
`python3.7 -m wkcuber.convert_knossos --layer_name color /media/data_cifs/connectomics/mag2 /media/data_cifs/connectomics/cubed_mag2`

This locked up midway through when I tried it last time. I may have to write scripts to do this directly using wkw.

**Comment by drewlinsley** [comment]
Conversion was mostly successful. There might be a few locations that are absent. Reopen if anyone notices this.

**Comment by David-Berson** [comment]
Yes, I see the intermediate levels now. No indication of gaps, but if we find any we'll let you know.
